env:
  - esnext
extends:
  - eslint:recommended
overrides:
  - extends: .eslintrc.typescript.yml
    files:
      - '**/*.mts'
      - '**/*.ts'
      - '**/*.tsx'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - prettier
root: true
rules:
  prettier/prettier: error
  no-empty:
    - error
    - allowEmptyCatch: true
